project:
  type: website
  output-dir: docs
website:
  title: "scattered-thoughts"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jeffufpost
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: sandstone
    css: styles.css



